export default {
  ADDRESS_LOAD: 'ADDRESS_LOAD',
  ADDRESS_FETCH: 'ADDRESS_FETCH',
  ADDRESS_ERROR: 'ADDRESS_ERROR',
  WEATHER_LOAD: 'WEATHER_LOAD',
  WEATHER_FETCH: 'WEATHER_FETCH',
  WEATHER_ERROR: 'WEATHER_ERROR',
};
